// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MVC_ORM_TEST
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.457")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Login - Use 'LoginParams' to pass parameters into this method.
        /// </summary>
        public void Login()
        {
            #region Variable Declarations
            HtmlEdit uIUserNameInputEdit = this.UISuccessforAllFoundatWindow.UIHttplocalhost38441LoDocument.UIUserNameInputEdit;
            HtmlEdit uIPasswordInputEdit = this.UISuccessforAllFoundatWindow.UIHttplocalhost38441LoDocument.UIPasswordInputEdit;
            HtmlInputButton uILoginButton = this.UISuccessforAllFoundatWindow.UIHttplocalhost38441LoDocument.UILoginButton;
            #endregion

            // Go to web page 'http://localhost:38441/' using new browser instance
            this.UISuccessforAllFoundatWindow.LaunchUrl(new System.Uri(this.LoginParams.UISuccessforAllFoundatWindowUrl));

            // Type 'ptwdemo' in 'userNameInput' text box
            uIUserNameInputEdit.Text = this.LoginParams.UIUserNameInputEditText;

            // Type '{Tab}' in 'userNameInput' text box
            Keyboard.SendKeys(uIUserNameInputEdit, this.LoginParams.UIUserNameInputEditSendKeys, ModifierKeys.None);

            // Type '********' in 'passwordInput' text box
            uIPasswordInputEdit.Password = this.LoginParams.UIPasswordInputEditPassword;

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(32, 21));
        }
        
        /// <summary>
        /// Login1 - Use 'Login1Params' to pass parameters into this method.
        /// </summary>
        public void Login1()
        {
            #region Variable Declarations
            HtmlEdit uIUserNameInputEdit = this.UISuccessforAllFoundatWindow.UIHttplocalhost38441LoDocument.UIUserNameInputEdit;
            HtmlEdit uIPasswordInputEdit = this.UISuccessforAllFoundatWindow.UIHttplocalhost38441LoDocument.UIPasswordInputEdit;
            #endregion

            // Go to web page 'http://localhost:38441/' using new browser instance
            this.UISuccessforAllFoundatWindow.LaunchUrl(new System.Uri(this.Login1Params.UISuccessforAllFoundatWindowUrl));

            // Type 'ptwdemo' in 'userNameInput' text box
            uIUserNameInputEdit.Text = this.Login1Params.UIUserNameInputEditText;

            // Type '{Tab}' in 'userNameInput' text box
            Keyboard.SendKeys(uIUserNameInputEdit, this.Login1Params.UIUserNameInputEditSendKeys, ModifierKeys.None);

            // Type '********' in 'passwordInput' text box
            uIPasswordInputEdit.Password = this.Login1Params.UIPasswordInputEditPassword;

            // Type '{Enter}' in 'passwordInput' text box
            Keyboard.SendKeys(uIPasswordInputEdit, this.Login1Params.UIPasswordInputEditSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual LoginParams LoginParams
        {
            get
            {
                if ((this.mLoginParams == null))
                {
                    this.mLoginParams = new LoginParams();
                }
                return this.mLoginParams;
            }
        }
        
        public virtual Login1Params Login1Params
        {
            get
            {
                if ((this.mLogin1Params == null))
                {
                    this.mLogin1Params = new Login1Params();
                }
                return this.mLogin1Params;
            }
        }
        
        public UISuccessforAllFoundatWindow UISuccessforAllFoundatWindow
        {
            get
            {
                if ((this.mUISuccessforAllFoundatWindow == null))
                {
                    this.mUISuccessforAllFoundatWindow = new UISuccessforAllFoundatWindow();
                }
                return this.mUISuccessforAllFoundatWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginParams mLoginParams;
        
        private Login1Params mLogin1Params;
        
        private UISuccessforAllFoundatWindow mUISuccessforAllFoundatWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.457")]
    public class LoginParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:38441/' using new browser instance
        /// </summary>
        public string UISuccessforAllFoundatWindowUrl = "http://localhost:38441/";
        
        /// <summary>
        /// Type 'ptwdemo' in 'userNameInput' text box
        /// </summary>
        public string UIUserNameInputEditText = "ptwdemo";
        
        /// <summary>
        /// Type '{Tab}' in 'userNameInput' text box
        /// </summary>
        public string UIUserNameInputEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'passwordInput' text box
        /// </summary>
        public string UIPasswordInputEditPassword = "SpFUCMEobWUJHcxL+f4CKiyeTzAgLXp5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Login1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.457")]
    public class Login1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:38441/' using new browser instance
        /// </summary>
        public string UISuccessforAllFoundatWindowUrl = "http://localhost:38441/";
        
        /// <summary>
        /// Type 'ptwdemo' in 'userNameInput' text box
        /// </summary>
        public string UIUserNameInputEditText = "ptwdemo";
        
        /// <summary>
        /// Type '{Tab}' in 'userNameInput' text box
        /// </summary>
        public string UIUserNameInputEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'passwordInput' text box
        /// </summary>
        public string UIPasswordInputEditPassword = "SpFUCMEobWUJHcxL+f4CKiyeTzAgLXp5";
        
        /// <summary>
        /// Type '{Enter}' in 'passwordInput' text box
        /// </summary>
        public string UIPasswordInputEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.457")]
    public class UISuccessforAllFoundatWindow : BrowserWindow
    {
        
        public UISuccessforAllFoundatWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Success for All Foundation Intranet";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Success for All Foundation Intranet");
            this.WindowTitles.Add("http://localhost:38441/Login");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttplocalhost38441LoDocument UIHttplocalhost38441LoDocument
        {
            get
            {
                if ((this.mUIHttplocalhost38441LoDocument == null))
                {
                    this.mUIHttplocalhost38441LoDocument = new UIHttplocalhost38441LoDocument(this);
                }
                return this.mUIHttplocalhost38441LoDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttplocalhost38441LoDocument mUIHttplocalhost38441LoDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.40219.457")]
    public class UIHttplocalhost38441LoDocument : HtmlDocument
    {
        
        public UIHttplocalhost38441LoDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:38441/Login";
            this.WindowTitles.Add("http://localhost:38441/Login");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUserNameInputEdit
        {
            get
            {
                if ((this.mUIUserNameInputEdit == null))
                {
                    this.mUIUserNameInputEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameInputEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "userNameInput";
                    this.mUIUserNameInputEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIUserNameInputEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUserNameInputEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserNameInputEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserNameInputEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUserNameInputEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=\"userNameInput\" type=\"text\" placehold";
                    this.mUIUserNameInputEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUserNameInputEdit.WindowTitles.Add("http://localhost:38441/Login");
                    #endregion
                }
                return this.mUIUserNameInputEdit;
            }
        }
        
        public HtmlEdit UIPasswordInputEdit
        {
            get
            {
                if ((this.mUIPasswordInputEdit == null))
                {
                    this.mUIPasswordInputEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordInputEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "passwordInput";
                    this.mUIPasswordInputEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIPasswordInputEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordInputEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordInputEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordInputEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordInputEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=\"passwordInput\" type=\"password\" place";
                    this.mUIPasswordInputEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordInputEdit.WindowTitles.Add("http://localhost:38441/Login");
                    #endregion
                }
                return this.mUIPasswordInputEdit;
            }
        }
        
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = "postLogin";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Login";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"postLogin\" type=\"button\" value=\"Logi";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUILoginButton.WindowTitles.Add("http://localhost:38441/Login");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUserNameInputEdit;
        
        private HtmlEdit mUIPasswordInputEdit;
        
        private HtmlInputButton mUILoginButton;
        #endregion
    }
}
